image: php:8.1

stages:
  - build
  - test
  - deploy

variables:
  APP_ENV: testing
  DB_DATABASE: ci4_test
  DB_USERNAME: root
  DB_PASSWORD: secret
  CI_ENVIRONMENT: testing

before_script:
  - apt-get update && apt-get install -y unzip curl git libzip-dev
  - docker-php-ext-install zip pdo pdo_mysql
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction --prefer-dist

build:
  stage: build
  script:
    - echo "Build process running..."

test:
  stage: test
  script:
    - vendor/bin/phpunit

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying application..."
    - rsync -avz --exclude 'writable/cache/*' ./ user@server:/var/www/html/

